=== KDE/kremotecontrol/profiles/old/profile.dtd
<!ELEMENT profile (name, author, instances?, action+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT action (name, comment, argument*)>
<!ELEMENT argument (comment, range?, default?)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT instances EMPTY>
<!ELEMENT range EMPTY>
<!ELEMENT default (#PCDATA)>

<!ATTLIST profile id CDATA #REQUIRED>
<!ATTLIST profile servicename CDATA #REQUIRED>
<!ATTLIST action objid CDATA #REQUIRED>
<!ATTLIST action prototype CDATA #REQUIRED>
<!ATTLIST argument type (int|uint|QString|QCString|QStringList|bool|double) #REQUIRED>
<!ATTLIST range min CDATA #REQUIRED>
<!ATTLIST range max CDATA #REQUIRED>
<!--
Here you can define the solid button name which triggers the action
To get a list  of all available button names please look at
http://api.kde.org/4.x-api/kdebase-workspace-apidocs/libs/solid/html/classSolid_1_1Control_1_1RemoteControlButton.html
-->
<!ATTLIST action button 
(Number0|Number1|Number2| 
Number3|Number4|Number5|Number6|
Number7|Number8|Number9|Play|
Pause|PlayPause|Stop|SkipForward|
SkipBackward|FastForward|Rewind|ChannelDown|
ChannelUp|VolumeDown|VolumeUp|Mute|
Info|Eject|Power|Up|
Down|Left|Right|Select|
Back|Menu|Aux|CD|
DVD|EPG|Favorites|Help|
Home|Music|Text|TV|
Blue|Green|Red|Yellow)
 #IMPLIED>

<!ATTLIST action multiplier CDATA "1">
<!ATTLIST action repeat (0|1) "0">
<!ATTLIST action autostart (0|1) "0">
<!ATTLIST instances unique (0|1) "1">
<!ATTLIST instances ifmulti (sendtotop|sendtobottom|sendtoall|dontsend) "dontsend">

=== KDE/kremotecontrol/profiles/old/suspend.profile.xml
<?xml version="1.0" ?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile id="Suspend" servicename="org.kde.klauncher">
	<name>Supend or Hibernate</name>
	<author>Michael Zanetti</author>
	<action objid="KLauncher" prototype="void kdeinit_exec(QString, QStringList, QStringList, QString)" repeat="0" autostart="0">
		<name>To RAM</name>
		<comment>Suspends your computer to RAM</comment>
		<argument type="QString">
			<comment>System command to use for suspend</comment>
			<default>solid-powermanagement</default>
		</argument>
		<argument type="QStringList">
			<comment>Parameters for the suspend commands</comment>
			<default>suspend,to_ram</default>
		</argument>
		<argument type="QStringList"><comment>Environment variables</comment></argument>
		<argument type="QString"><comment>Startup ID</comment></argument>
	</action>
	<action objid="KLauncher" prototype="void kdeinit_exec_wait(QString, QStringList, QStringList, QString)" repeat="0" autostart="0">
		<name>To disk</name>
		<comment>Suspends your computer disk (hibernate)</comment>
		<argument type="QString">
			<comment>System command to use for suspend</comment>
			<default>solid-powermanagement</default>
		</argument>
		<argument type="QStringList">
			<comment>Parameters for the suspend commands</comment>
			<default>suspend,to_disk</default>
		</argument>
		<argument type="QStringList"><comment>Environment variables</comment></argument>
		<argument type="QString"><comment>Startup ID</comment></argument>
	</action>
</profile>

=== KDE/kremotecontrol/profiles/old/okular.profile.xml
<?xml version="1.0" ?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile id="okular" servicename="org.kde.okular">
    <name>Okular</name>
    <author>Pino Toscano</author>
    <instances unique="0" ifmulti="sendtotop"/>
    <action objid="okular" prototype="void slotPreviousPage()" repeat="0" autostart="0" button="Rewind">
        <name>Back</name>
        <comment>Goes to the previous page</comment>
    </action>
    <action objid="okular" prototype="void slotNextPage()" repeat="0" autostart="0" button="FastForward">
        <name>Forward</name>
        <comment>Goes to the next page</comment>
    </action>
    <action objid="okular" prototype="void slotGotoFirst()" repeat="0" autostart="0" button="SkipBackward">
        <name>First</name>
        <comment>Goes to the first page</comment>
    </action>
    <action objid="okular" prototype="void slotGotoLast()" repeat="0" autostart="0" button="SkipForward">
        <name>Last</name>
        <comment>Goes to the last page</comment>
    </action>
    <action objid="okular" prototype="void slotTogglePresentation()" repeat="0" autostart="0" class="PlayPause">
        <name>Presentation</name>
        <comment>Starts/stops presentation</comment>
    </action>
    <action objid="okular" prototype="void reload()" repeat="0" autostart="0">
        <name>Reload</name>
        <comment>Reloads the open document</comment>
    </action>
    <action objid="okular" prototype="void goToPage(uint)" repeat="0" autostart="0">
        <name>Go to Page</name>
        <comment>Goes to the specified page</comment>
        <argument type="uint"><comment>The page to choose</comment><default>1</default></argument>
    </action>
    <action objid="okular" prototype="void openDocument(QString)" repeat="0" autostart="0">
        <name>Open document</name>
        <comment>Opens a document</comment>
        <argument type="QString"><comment>The document to be open</comment></argument>
    </action>
</profile>

=== KDE/kremotecontrol/profiles/old/kmix.profile.xml
<?xml version="1.0" ?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile id="kmix" servicename="org.kde.kmix">
    <name>Sound Mixer</name>
    <author>Michael Zanetti</author>
    <instances unique="1"/>
    <action objid="Mixer0" prototype="void increaseVolume(QString)" repeat="1" button="VolumeUp">
        <name>Increase Volume</name>
        <comment></comment>
        <argument type="QString">
            <comment>The name of the slider you want to move and its index separated by a colon (eg. Master:0)</comment>
            <default>Master:0</default>
        </argument>
    </action>
    <action objid="Mixer0" prototype="void decreaseVolume(QString)" repeat="1" button="VolumeDown">
        <name>Decrease Volume</name>
        <comment></comment>
        <argument type="QString">
            <comment>The name of the slider you want to move and its index separated by a colon (eg. Master:0)</comment>
            <default>Master:0</default>
        </argument>
    </action>
    <action objid="Mixer0" prototype="void toggleMute(QString)" button="Mute">
        <name>Toggle Mute</name>
        <comment></comment>
        <argument type="QString">
            <comment>The name of the slider you want to mute and its index separated by a colon (eg. Master:0)</comment>
            <default>Master:0</default>
        </argument>
    </action>
</profile>

=== KDE/kremotecontrol/profiles/shutdown.profile.xml
<?xml version="1.0" ?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile id="Shutdown" servicename="org.kde.ksmserver">
	<name>Shutdown or reboot</name>
	<author>Michael Zanetti</author>
	<action objid="KSMServer" prototype="void logout(int, int, int)" repeat="0" autostart="0">
		<name>logout</name>
		<comment>Logout and shutdown or reboot your computer</comment>
		<argument type="int">
			<comment>Ask for confirmation? 1 = No, 2 = Yes</comment>
			<default>2</default>
		</argument>
		<argument type="int">
			<comment>Shutdown? 1 = Reboot, 2 = Halt, 3 = Logout</comment>
			<default>2</default>
		</argument>
		<argument type="int">
			<comment>When? 0 = When ready, 1 = Try now, 2 = Force now, 3 = Interactive</comment>
			<default>2</default>
		</argument>
	</action>
</profile>

=== KDE/kremotecontrol/profiles/dragonplayer.profile.xml
<?xml version="1.0" ?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile id="dragonplayer" servicename="org.mpris.dragonplayer">
    <name>Dragon Player</name>
    <author>Gioacchino Mazzurco [gmazzurco89@gmail.com]</author>
    <instances unique="0" ifmulti="sendtoone"/>

    <!-- Playback actions -->
    <action objid="Player" prototype="void Play()" class="play" button="Play">
        <name>Start playing</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Stop()" class="stop" button="Stop">
        <name>Stop playing</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Pause()" class="pause" button="PlayPause">
        <name>Pause playing</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Next()" class="next" button="SkipForward">
        <name>Advance to next track</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Prev()" class="previous" button="SkipBackward">
        <name>Go to previous track</name>
        <comment></comment>
    </action>
</profile>

=== KDE/kremotecontrol/profiles/old/konqueror.profile.xml
<?xml version="1.0"?>
<!DOCTYPE profile SYSTEM "profile.dtd">

<profile id="konqueror" servicename="org.kde.konqueror">
	<name>Konqueror</name>
	<author>Gav Wood</author>
	<instances unique="0" ifmulti="sendtotop"/>
	<action objid="KonqMain" prototype="void openBrowserWindow(QString, QByteArray)" repeat="0" autostart="0">
		<name>Create New Window</name>
		<comment>Creates a new window and loads an arbitrary URL.</comment>
		<argument type="QString"><comment>The URL to load in the window initially.</comment></argument>
		<argument type="QByteArray"><comment>Startup Id</comment></argument>
	</action>
	<action objid="MainApplication" prototype="void quit()" repeat="0" autostart="0">
		<name>Quit</name>
		<comment>Closes the Konqueror window.</comment>
	</action>
</profile>

=== KDE/kremotecontrol/profiles/amarok.profile.xml
<?xml version="1.0" ?>
<!DOCTYPE profile SYSTEM "profile.dtd">
<profile id="amarok" servicename="org.mpris.amarok">
    <name>Amarok</name>
    <author>Dirk Ziegelmeier</author>
    <instances unique="1"/>

    <!-- Playback actions -->
    <action objid="Player" prototype="void Play()" button="Play">
        <name>Start playing</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Stop()" button="Stop">
        <name>Stop playing</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Pause()" button="PlayPause">
        <name>Pause playing</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Next()" button="SkipForward">
        <name>Advance to next track</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Prev()"  button ="SkipBackward">
        <name>Go to previous track</name>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Forward(int)" button="Forward">
        <name>Fast Forward</name>
        <argument type="int">
            <comment>Amount to fast forward in ms</comment>
            <default>10000</default>
        </argument>
        <comment></comment>
    </action>
    <action objid="Player" prototype="void Backward(int)"  button ="Rewind">
        <name>Rewind</name>
        <argument type="int">
            <comment>Amount to rewind in ms</comment>
            <default>10000</default>
        </argument>
        <comment></comment>
    </action>
</profile>

=== KDE/kremotecontrol/profiles/noatun.profile.xml
<?xml version="1.0" ?>
<!DOCTYPE profile SYSTEM "profile.dtd">

<profile id="noatun" serivename="Noatun">
	<name>Noatun</name>
	<author>Gav Wood</author>
	<action objid="Noatun" prototype="void playpause()" class="pause">
		<name>Play/Pause</name>
		<comment>Toggles the current track between playing and pausing.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void stop()" class="stop">
		<name>Stop</name>
		<comment>Stops current playback, if any.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void clear()" class="eject">
		<name>Clear Playlist</name>
		<comment>Clears the playlist of all items.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void back()" class="previous">
		<name>Back</name>
		<comment>Skips to the start of the last track.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void forward()" class="next">
		<name>Forward</name>
		<comment>Skips to the start of the next track.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void loop()">
		<name>Playback Mode</name>
		<comment>Cycles through the playback modes of Noatun.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void play()" class="play">
		<name>Play</name>
		<comment>Starts playback.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void removeCurrent()">
		<name>Remove Current</name>
		<comment>Removes only the current track from the play list.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void setVolume()">
		<name>Set Volume</name>
		<comment>Sets the volume to a configurable amount.</comment>
		<arguments count="1">
			<argument place="0">
				<comment>The required percentage of the volume.</comment>
				<type>int</type>
				<range min="0" max="100"/>
			</argument>
		</arguments>
	</action>
	<action objid="Noatun" prototype="void toggleListView()">
		<name>Toggle Playlist View</name>
		<comment>Toggles the visiblility of the playlist window.</comment>
		<arguments/>
	</action>
	<action objid="Noatun" prototype="void skipto(int)">
		<name>Skip To</name>
		<comment>Skips to a configurable point in the current track.</comment>
		<arguments count="1">
			<argument place="0">
				<comment>The percentage of the track to move through.</comment>
				<type>int</type>
				<range min="0" max="100"/>
			</argument>
		</arguments>
	</action>
</profile>
