=== KDE/kremotecontrol/remotes/remote.dtd
<!DOCTYPE remote [

<!ELEMENT remote (button+, name, author)>
<!ELEMENT button (name)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>

<!ATTLIST remote id CDATA #REQUIRED>
<!ATTLIST button id CDATA #REQUIRED>

]>

=== KDE/kremotecontrol/remotes/hauppauge.remote.xml
<?xml version="1.0" ?>
<!DOCTYPE remote SYSTEM "remote.dtd">

<remote id="Hauppauge">
	<name>Hauppauge</name>
	<author>Dirk Ziegelmeier</author>
	<information>Bundled with WinTV PCI, PVR</information>
	<button id="0" class="number" parameter="0"/>
	<button id="1" class="number" parameter="1"/>
	<button id="2" class="number" parameter="2"/>
	<button id="3" class="number" parameter="3"/>
	<button id="4" class="number" parameter="4"/>
	<button id="5" class="number" parameter="5"/>
	<button id="6" class="number" parameter="6"/>
	<button id="7" class="number" parameter="7"/>
	<button id="8" class="number" parameter="8"/>
	<button id="9" class="number" parameter="9"/>
	<button id="TV"><name>TV</name></button>
	<button id="RADIO"><name>Radio</name></button>
	<button id="CH-" class="channeldown"><name>Channel Down</name></button>
	<button id="CH+" class="channelup"><name>Channel Up</name></button>
	<button id="VOL-" class="volumedown"><name>Volume Down</name></button>
	<button id="VOL+" class="volumeup"><name>Volume Up</name></button>
	<button id="MUTE" class="mute"><name>Mute</name></button>
	<button id="SOURCE"><name>Source</name></button>
	<button id="FULL_SCREEN" class="fullscreen"><name>Fullscreen</name></button>
	<button id="RESERVED"><name>Reserved</name></button>
	<button id="MINIMIZE"><name>Minimize</name></button>
</remote>

=== KDE/kremotecontrol/remotes/AsusDH.remote.xml
<?xml version="1.0" ?>
<!DOCTYPE remote SYSTEM "remote.dtd">

<remote id="AsusDH">
        <name>Asus Digital Home</name>
        <author>Gioacchino Mazzurco</author>
        <information>Bundled with all Asus Digital Home motherboard series</information>
        <button id="POWER" class="power"><name>Power</name></button>
        <button id="QUICK_POWER" class="quickpower"><name>Quick Power</name></button>
        <button id="NOISE_OFF" class="noiseoff"><name>Noise Off</name></button>
        <button id="WIFI" class="wifi"><name>Wi Fi</name></button>
        <button id="AP_LAUNCH" class="aplaunch"><name>Launch App</name></button>
        <button id="MAXIMIZE" class="maximize"><name>Maximize</name></button>
        <button id="PLUS" class="volup"><name>Volume +</name></button>
        <button id="REV" class="rev"><name>Previous</name></button>
        <button id="PLAY/PAUSE" class="playpause"><name>Play / Pause</name></button>
        <button id="FWD" class="fwd"><name>Next</name></button>
        <button id="MINUS" class="volumedown"><name>Volume -</name></button>
</remote>

=== KDE/kremotecontrol/remotes/sonytv.remote.xml
<?xml version="1.0" ?>
<!DOCTYPE remote SYSTEM "remote.dtd">

<remote id="SONY-TV">
	<name>SonyTV</name>
	<information>Bundled with some Sony TVs</information>
	<author>Dirk Ziegelmeier</author>
	<button id="0" class="number" parameter="0"/>
	<button id="1" class="number" parameter="1"/>
	<button id="2" class="number" parameter="2"/>
	<button id="3" class="number" parameter="3"/>
	<button id="4" class="number" parameter="4"/>
	<button id="5" class="number" parameter="5"/>
	<button id="6" class="number" parameter="6"/>
	<button id="7" class="number" parameter="7"/>
	<button id="8" class="number" parameter="8"/>
	<button id="9" class="number" parameter="9"/>
	<button id="TV"><name>TV</name></button>
	<button id="CHANNELDOWN" class="channeldown"><name>Channel Down</name></button>
	<button id="CHANNELUP" class="channelup"><name>Channel Up</name></button>
	<button id="VOLUMEDOWN" class="volumedown"><name>Volume Down</name></button>
	<button id="VOLUMEUP" class="volumeup"><name>Volume Up</name></button>
	<button id="MUTE" class="mute"><name>Mute</name></button>
	<button id="EXT"><name>EXT</name></button>
	<button id="-/--"><name>-/--</name></button>
	<button id="RED"><name>Red</name></button>
	<button id="YELLOW"><name>Yellow</name></button>
	<button id="BLUE"><name>Blue</name></button>
	<button id="GREEN"><name>Green</name></button>
</remote>

=== KDE/kremotecontrol/remotes/packbell.remote.xml
<?xml version="1.0" ?>
<!DOCTYPE remote SYSTEM "remote.dtd">

<remote id="PackBell">
	<name>Packbell Remote Control</name>
	<author>Frank Scheffold</author>
	
	<button id="Help"><name>Help</name></button>
	<button id="Phone"><name>Phone</name></button>
	<button id="Message"><name>Message</name></button>
	<button id="SRS"><name>SRS</name></button>
	
	<button id="CD"><name>Input CD</name></button>
	<button id="Aux1"><name>Input Aux1</name></button>
	<button id="Aux2"><name>Input Aux2</name></button>
	<button id="Aux3"><name>Input Aux3</name></button>
	
	<button id="Up" class="play"><name>Up</name></button>	
	<button id="Down" class="stop"><name>Down</name></button>
	<button id="Left" class="previous"><name>Left</name></button>
	<button id="Right" class="next"><name>Right</name></button>	
	<button id="RMB" class="forward"><name>Right mouse button</name></button>
	<button id="LMB" class="rewind"><name>Left mouse button</name></button>
	
	<button id="Menu"><name>Menu</name></button>
	<button id="Enter" class="enter"><name>Enter</name></button>
	<button id="Display" class="fullscreen"><name>Display</name></button>
	<button id="Mute" class="mute"><name>Mute</name></button>
	<button id="CHUp" class="channelup"><name>Chanel Up</name></button>
	<button id="CHDown" class="channeldown"><name>Chanel Down</name></button>
	<button id="VolUp" class="volumeup"><name>Volume Up</name></button>
	<button id="VolDown" class="volumedown"><name>Volume Down</name></button>
	
	<button id="00" class="number" parameter="0"><name>0</name></button>
	<button id="01" class="number" parameter="1"><name>1</name></button>
	<button id="02" class="number" parameter="2"><name>2</name></button>
	<button id="03" class="number" parameter="3"><name>3</name></button>
	<button id="04" class="number" parameter="4"><name>4</name></button>
	<button id="05" class="number" parameter="5"><name>5</name></button>
	<button id="06" class="number" parameter="6"><name>6</name></button>
	<button id="07" class="number" parameter="7"><name>7</name></button>
	<button id="08" class="number" parameter="8"><name>8</name></button>
	<button id="09" class="number" parameter="9"><name>9</name></button>	
	<button id="Star"><name>Star</name></button>
	<button id="Hash"><name>Hash</name></button>
</remote>

=== KDE/kremotecontrol/remotes/RM-0010.remote.xml
<?xml version="1.0" ?>
<!DOCTYPE remote SYSTEM "remote.dtd">

<remote id="RM-0010">
	<name>Leadtek CoolCommand RM-0010</name>
	<author>Zsolt Rizsanyi</author>
	<button id="0" class="number" parameter="0"/>
	<button id="1" class="number" parameter="1"/>
	<button id="2" class="number" parameter="2"/>
	<button id="3" class="number" parameter="3"/>
	<button id="4" class="number" parameter="4"/>
	<button id="5" class="number" parameter="5"/>
	<button id="6" class="number" parameter="6"/>
	<button id="7" class="number" parameter="7"/>
	<button id="8" class="number" parameter="8"/>
	<button id="9" class="number" parameter="9"/>
	<button id="POWER" class="off"><name>Power</name></button>
	<button id="TV/FM"><name>TV/FM</name></button>
	<button id="SCAN" class="scan"><name>Scan</name></button>
	<button id="DISPLAY"><name>Display</name></button>
	<button id="RECALL" class="recall"><name>Recall</name></button>
	<button id="ENTER" class="enter"><name>Enter</name></button>
	<button id="CC" class="captions"><name>Closed Captions</name></button>
	<button id="MTS"><name>MTS</name></button>
	<button id="FINE_DOWN" class="finetunedown"><name>Fine Tune Down</name></button>
	<button id="FINE_UP" class="finetuneup"><name>Fine Tune Up</name></button>
	<button id="VIDEO"><name>Video</name></button>
	<button id="MUTE" class="mute"><name>Mute</name></button>
	<button id="CH_UP" class="channelup"><name>Channel Up</name></button>
	<button id="CH_DOWN" class="channeldown"><name>Channel Down</name></button>
	<button id="VOL_UP" class="volumeup"><name>Volume Up</name></button>
	<button id="VOL_DOWN" class="volumedown"><name>Volume Down</name></button>
	<button id="FULLSCREEN" class="fullscreen"><name>Full Screen</name></button>
	<button id="SLEEP"><name>Sleep</name></button>
	<button id="BOSS_KEY"><name>Boss key</name></button>
	<button id="RED" class="red"><name>Red</name></button>
	<button id="GREEN" class="green"><name>Green</name></button>
	<button id="YELLOW" class="yellow"><name>Yellow</name></button>
	<button id="BLUE" class="blue"><name>Blue</name></button>
	<button id="PIP"><name>Pip</name></button>
	<button id="."><name>Dot (.)</name></button>
	<button id="BACK" class="previous"><name>Back</name></button>
	<button id="PLAY" class="play"><name>Play</name></button>
	<button id="NEXT" class="next"><name>Next</name></button>
	<button id="TIMESHIFT"><name>Timeshift</name></button>
	<button id="STOP" class="stop"><name>Stop</name></button>
	<button id="REC" class="record"><name>Record</name></button>
	<button id="SNAPSHOT"><name>Snapshot</name></button>
</remote>

=== KDE/kremotecontrol/remotes/SL-6399.remote.xml
<?xml version="1.0" ?>
<!DOCTYPE remote SYSTEM "remote.dtd">

<remote id="SL-6399">
	<name>Speed Link 6399 Remote Control</name>
	<author>Frank Scheffold</author>

	<information>Speed Link 6399 Media Control Remote (own lircd.conf)</information>
	<button id="ZERO" class="number" parameter="0"/>
	<button id="ONE" class="number" parameter="1"/>
	<button id="TWO" class="number" parameter="2"/>
	<button id="THREE" class="number" parameter="3"/>
	<button id="FOUR" class="number" parameter="4"/>
	<button id="FIVE" class="number" parameter="5"/>
	<button id="SIX" class="number" parameter="6"/>
	<button id="SEVEN" class="number" parameter="7"/>
	<button id="EIGHT" class="number" parameter="8"/>
	<button id="NINE" class="number" parameter="9"/>
	<button id="PC" class="off"><name>Power</name></button>
	<button id="TV"><name>TV/FM</name></button>
		
	<button id="OK" class="enter"><name>Enter</name></button>
	
	<button id="MUTE" class="mute"><name>Mute</name></button>
	<button id="CH_UP" class="channelup"><name>Channel Up</name></button>
	<button id="CH_DOWN" class="channeldown"><name>Channel Down</name></button>
	<button id="VOL_UP" class="volumeup"><name>Volume Up</name></button>
	<button id="VOL_DOWN" class="volumedown"><name>Volume Down</name></button>



	<button id="VIDEOS" class="red"><name>Red</name></button>
	<button id="MUSIC" class="green"><name>Green</name></button>
	<button id="PICTURES" class="yellow"><name>Yellow</name></button>
	<button id="MYTV" class="blue"><name>Blue</name></button>
	
	
	
	
	<button id="REW" class="previous"><name>Back</name></button>
	<button id="PLAY" class="play"><name>Play</name></button>
	<button id=FFW" class="next"><name>Next</name></button>
	
	<button id="STOP" class="stop"><name>Stop</name></button>
	<button id="RECORD" class="record"><name>Record</name></button>
	
	
	<button id="UP">Up</button>
	<button id="DOWN">Down</button>
	<button id="LEFT">Left</button>
	<button id="RIGHT">Right</button>
	
</remote>

=== KDE/kremotecontrol/remotes/AppleRemote.remote.xml
<?xml version="1.0" ?>
<!DOCTYPE remote SYSTEM "remote.dtd">

<remote id="AppleRemote">
	<name>Apple Remote</name>
	<author>Michael Zanetti</author>
	<information>Bundled with all Intel powered Apple Computers and some late MacMini PPC models</information>
	<button id="Menu" class="enter"><name>Menu</name></button>
	<button id="Play" class="play"><name>Play</name></button>
	<button id="Vol+" class="volumeup"><name>Volume Up</name></button>
	<button id="Vol-" class="volumedown"><name>Volume Down</name></button>
	<button id="Rew" class="previous"><name>Rewind</name></button>
	<button id="Fwd" class="next"><name>Forward</name></button>
	
</remote>
